const btn = document.getElementById('btn');
const quotes = [
    ['Hayatı ve özgürlüğü için ölümü göze alan bir millet asla yenilmez. ', 'Mustafa Kemal Atatürk'],
    ['Benim naçiz vücudum elbet bir gün toprak olacaktır, ancak Türkiye Cumhuriyeti ilelebet payidar kalacaktır.','Mustafa Kemal Atatürk'],
    ['Dünyada her şey için, medeniyet için, hayat için, başarı için, en hakiki mürşit bilimdir, fendir.', 'Mustafa Kemal Atatürk'],
    ['İmkanın sınırını görmek için imkansızı denemek lazım.', 'Fatih Sultan Mehmet'],
    ['Baykuştan korkumuz yok! biz ki, şahinler sürüsü.','Fatih Sultan Mehmet'],
    ['Dün akıllıydım, dünyayı değiştirmek istedim; Bugün ise bilgeyim, Kendimi Değiştirdim.','Mevlana'],
    ['Köpeklerin kardeşliği, aralarına kemik atana kadardır.','Mevlana'],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['',''],
    ['','']

]